### ISSUE TITLE
pandas can't read_parquet Embedded File:- BioBertFolder/bertffn_crossentropy.zip

### ISSUE THREAD

**Issue by Tonytony123474** [re-search/DocProduct#21]
in predictor.py> Class FaissTopK >   self.df = pd.read_parquet(self.embedding_file)
embedding_file="BioBertFolder/bertffn_crossentropy.zip"
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'. pyarrow or fastparquet is required for parquet support

and also manually i can't extract that zip file.

**Comment by WrathofBhuvan11** [comment]
Pip install pyarrow

**Comment by Santosh-Gupta** [comment]
can you make a colab notebook which reproduces the error?

**Comment by Tonytony123474** [comment]
> Pip install pyarrow

Yes it's working..
