### ISSUE TITLE
ImportError: cannot import name 'export_saved_model'

### ISSUE THREAD

**Issue by darshakpranpariya** [re-search/DocProduct#25]
This error is showing while installing !pip install tensorflow-gpu==2.0.0-alpha0.
How can i resolve it, please help me out...

I have tried out this stackoverflow solution, but it did not working:-
https://stackoverflow.com/questions/60879608/tensorflow-raised-error-importerror-cannot-import-name-export-saved-model

**Comment by Santosh-Gupta** [comment]
This seems like an issue with Tensorflow and not DotProduct?

**Comment by darshakpranpariya** [comment]
yes brother, but any solution?

I have tried to install "pip install tensorflow-gpu==2.0.0.beta1" this version instead but still come up with same error.
code was working perfectly but this specific error started to come since tensorflow updated its version.

**Comment by Santosh-Gupta** [comment]
I haven't tested the repo in a while.
