### ISSUE TITLE
Google Colab not running

### ISSUE THREAD

**Issue by shari-amalgamrx** [re-search/DocProduct#28]
Hello Team,
I am unable to run the Google Colab. Can you please tell me where am I going wrong?

Apparently the tensor-flow has issues with the version. I am getting this issue when I run the " Load model weights and Q&A data. Double click to see code" cell.

AttributeError: module 'tensorflow' has no attribute 'compat'

**Comment by shari-amalgamrx** [comment]
Was able to solve it by,
1. 
!pip uninstall -y tensorflow
!pip uninstall tensorflow-estimator

2. 
! pip install tensorflow-estimator==2.1


#@title Install Faiss, TF 2.0, and our Github. Double Click to see code
#To use CPU FAISS use
!wget  https://anaconda.org/pytorch/faiss-cpu/1.2.1/download/linux-64/faiss-cpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
#To use GPU FAISS use
# !wget  https://anaconda.org/pytorch/faiss-gpu/1.2.1/download/linux-64/faiss-gpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
!tar xvjf faiss-cpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/
!pip install mkl
!pip install tensorflow-gpu==2.0.0-alpha0
!pip install https://github.com/re-search/DocProduct/archive/v0.2.0_dev.zip
!pip install gpt2-estimator
!pip install pyarrow


and then in a different cell I imported the tensorflow as tf

**Comment by Santosh-Gupta** [comment]
Thanks Shari, I guess some of the functions were deprecated
