### ISSUE TITLE
error while unzipping qa_embeddings/bertffn_crossentropy.zip

### ISSUE THREAD

**Issue by WrathofBhuvan11** [re-search/DocProduct#7]
models extraction worked fine but problem with qa_embeddings/bertffn_crossentropy.zip 
Shows "zip error: Zip file structure invalid (bertffn_crossentropy.zip)" error

**Comment by JayYip** [comment]
#4 #3

**Comment by JayYip** [comment]
This is a known issue caused by downloading from OneDrive failed. Currently we don't have a solution. You need to download the file manually through browser to avoid that. Sorry for the inconvenience that may cause.

**Comment by WrathofBhuvan11** [comment]
Hello thqs for the reply... Can u provide link for manual download of
this.. ?

**Comment by JayYip** [comment]
@WrathofBhuvan11 Please try this link: https://1drv.ms/u/s!An_n1-LB8-2dgoAYrXYnnBSA4d5dsg?e=FSgTNu

**Comment by Santosh-Gupta** [comment]
> @WrathofBhuvan11 Please try this link: https://1drv.ms/u/s!An_n1-LB8-2dgoAYrXYnnBSA4d5dsg?e=FSgTNu

If it's down it doesn't matter if you try to download it via browser or colab, the only solution is to wait a few hours and if it's open, upload it to your own drive so you'll always have it.
