### ISSUE TITLE
TypeError while running DocProduct/docproduct/prediction.py

### ISSUE THREAD

**Issue by WrathofBhuvan11** [re-search/DocProduct#8]
File "predictor.py", line 314, in <module>
    gen = GenerateQADoc()
  File "predictor.py", line 273, in __init__
    load_pretrain=False
  File "predictor.py", line 85, in __init__
    self.predict(questions=question, answers=answer, dataset=False)
  File "predictor.py", line 154, in predict
    model_outputs = self.model(model_inputs)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 703, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/models.py", line 114, in call
    (inputs['q_input_ids'], inputs['q_segment_ids'], inputs['q_input_masks']))[self.layer_ind]
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 703, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/bert.py", line 169, in call
    trainable=self.trainable)
  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/bert.py", line 141, in _wrap_layer
    build_output = build_func(input_layer)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 696, in __call__
    self.build(input_shapes)
  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/keras_bert/keras_multi_head/multi_head_attention.py", line 94, in build
    name='%s_Wq' % self.name,
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 534, in add_weight
    use_resource=use_resource)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 497, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1873, in make_variable
    use_resource=use_resource)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2196, in default_variable_creator
    constraint=constraint)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 312, in __init__
    constraint=constraint)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 417, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1860, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 468, in __call__
    scale /= max(1., (fan_in + fan_out) / 2.)
TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

**Comment by Santosh-Gupta** [comment]
Can you sent a link to the colab notebook you're using?

**Comment by WrathofBhuvan11** [comment]
I'm running on my system... i have all pretrained models ...
except ....
    loader('bert/embeddings/word_embeddings'), {here}
it's from keras_bert directory
actually i think i knw where's the mistake.. i think this word emebeddings is missing can i get the link of it 

  File "<ipython-input-78-2fdd214e0436>", line 1, in <module>
    runfile('/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/predictor.py', wdir='/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct')

  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/predictor.py", line 314, in <module>
    gen = GenerateQADoc()

  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/predictor.py", line 273, in __init__
    load_pretrain=True#False # <TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'>

  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/predictor.py", line 76, in __init__
    layer_ind=layer_ind)

  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/docproduct/models.py", line 87, in __init__
    model=self.biobert, config=config, checkpoint_file=checkpoint_file, training=False)

  File "/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/keras_bert/loader.py", line 72, in load_model_weights_from_checkpoint
    loader('bert/embeddings/word_embeddings'),

  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1462, in set_weights
    str(weights)[:50] + '...')

ValueError: You called `set_weights(weights)` on layer "Embedding-Token" with a  weight list of length 1, but the layer was expecting 0 weights. Provided weights: [array([[-0.03812443, -0.08015507, -0.01168962, .....

**Comment by Santosh-Gupta** [comment]
"i think this word emebeddings is missing can i get the link of it"

It's a little tricky to diagnose the exact issue. Could you post the code you are using?

**Comment by WrathofBhuvan11** [comment]
can I use keras_bert from "https://github.com/CyberZHG/keras-bert" ?
the code i'm using is...
 https://github.com/re-search/DocProduct/blob/master/keras_bert/loader.py
I'm using keras_bert folder from your git rep. I'm not sure from where to download bert word embeddings
line.no.57
def load_model_weights_from_checkpoint(model,
                                       config,
                                       checkpoint_file,
                                       training=False):
    """Load trained official model from checkpoint.
    :param model: Built keras model.
    :param config: Loaded configuration file.
    :param checkpoint_file: The path to the checkpoint files, should end with '.ckpt'.
    :param training: If training, the whole model will be returned.
                     Otherwise, the MLM and NSP parts will be ignored.
    """
the path you gave in this function defination...

**Comment by WrathofBhuvan11** [comment]
https://github.com/CyberZHG/keras-bert#download-pretrained-checkpoints 
does your keras_bert has these functions to download Bert word-embeddings?

**Comment by WrathofBhuvan11** [comment]
A Big problem is your rep. on gpt estimator or keras_bert doesn't support tf 1.9 it's tf 2.0 and i'm using anaconda and they didn't update to tf 2.0 it's still 1.9. Yesterday i had to write gpt2 estimator for tf 1.9.
Now prblm same for keras_bert....
Successfully built keras-bert keras-transformer keras-pos-embd keras-multi-head keras-layer-normalization keras-position-wise-feed-forward keras-embed-sim keras-self-attention
ERROR: docproduct 0.0.0 requires pyarrow, which is not installed.
ERROR: docproduct 0.0.0 requires tensorflow-gpu==2.0.0-alpha0, which is not installed.
ERROR: docproduct 0.0.0 has requirement keras-pos-embd==0.9.0, but you'll have keras-pos-embd 0.11.0 which is incompatible.
ERROR: docproduct 0.0.0 has requirement keras-transformer==0.21.0, but you'll have keras-transformer 0.28.0 which is incompatible.
ERROR: docproduct 0.0.0 has requirement tensorflow==2.0.0-alpha0, but you'll have tensorflow 1.9.0 which is incompatible.
Installing collected packages: keras-pos-embd, keras-self-attention, keras-multi-head, keras-layer-normalization, keras-position-wise-feed-forward, keras-embed-sim, keras-transformer, keras-bert
  Found existing installation: keras-pos-embd 0.9.0
    Uninstalling keras-pos-embd-0.9.0:
      Successfully uninstalled keras-pos-embd-0.9.0
  Found existing installation: keras-transformer 0.21.0
    Uninstalling keras-transformer-0.21.0:
      Successfully uninstalled keras-transformer-0.21.0
Successfully installed keras-bert-0.68.1 keras-embed-sim-0.7.0 keras-layer-normalization-0.12.0 keras-multi-head-0.20.0 keras-pos-embd-0.11.0 keras-position-wise-feed-forward-0.6.0 keras-self-attention-0.41.0 keras-transformer-0.28.0

**Comment by Santosh-Gupta** [comment]
Ah, interesting. I believe TF 2.0 is still in beta, so it may be a while before Anaconda is updated to 2.0.  This code is in TF 2.0 because we submitted it to a TF 2.0 hackathon.

**Comment by WrathofBhuvan11** [comment]
Yeah there's nothing that I can do. Actually i made gpt2estimator wrk for tf 1.9 but now should do the same for keras_bert

**Comment by WrathofBhuvan11** [comment]
In [43]: 



In [43]: config_file="/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/BioBertFolder/biobert_v1.0_pubmed_pmc/bert_config.json"



In [44]: from bert_ import build_model_from_config



In [45]: build_model_from_config(config_file)

Out[45]: 

(<bert_.Bert at 0x7fd86b408c18>,

 {'attention_probs_dropout_prob': 0.1,

  'hidden_act': 'gelu',

  'hidden_dropout_prob': 0.1,

  'hidden_size': 768,

  'initializer_range': 0.02,

  'intermediate_size': 3072,

  'max_position_embeddings': 512,

  'num_attention_heads': 12,

  'num_hidden_layers': 12,

  'type_vocab_size': 2,

  'vocab_size': 28996})



In [46]: load_model_weights_from_checkpoint(model,

    ...:                                        config,

    ...:                                        checkpoint_file,

    ...:                                        training=False)

    ...:                                        

Traceback (most recent call last):



  File "<ipython-input-46-1ccd4c852044>", line 1, in <module>

    load_model_weights_from_checkpoint(model,



NameError: name 'model' is not defined





In [47]: 



In [47]: model,config=build_model_from_config(config_file)



In [48]: model

Out[48]: <bert_.Bert at 0x7fd86aca7e10>



In [49]: config

Out[49]: 

{'attention_probs_dropout_prob': 0.1,

 'hidden_act': 'gelu',

 'hidden_dropout_prob': 0.1,

 'hidden_size': 768,

 'initializer_range': 0.02,

 'intermediate_size': 3072,

 'max_position_embeddings': 512,

 'num_attention_heads': 12,

 'num_hidden_layers': 12,

 'type_vocab_size': 2,

 'vocab_size': 28996}



In [50]: pretrained_path="/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/BioBertFolder/biobert_v1.0_pubmed_pmc/"



In [51]: 

    ...: checkpoint_file = os.path.join(

    ...:     pretrained_path, 'biobert_model.ckpt')

    ...:     



In [52]: checkpoint_file

Out[52]: '/home/bhuvanesh/Documents/pystuff/Medical_dr_source/DocProduct/BioBertFolder/biobert_v1.0_pubmed_pmc/biobert_model.ckpt'



In [53]: load_model_weights_from_checkpoint(model,

    ...:                                        config,

    ...:                                        checkpoint_file,

    ...:                                        training=False)

    ...:                                        

Traceback (most recent call last):



  File "<ipython-input-53-1ccd4c852044>", line 4, in <module>

    training=False)



  File "<ipython-input-22-e60d8ac633c6>", line 72, in load_model_weights_from_checkpoint

    loader('bert/embeddings/word_embeddings'),



  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1462, in set_weights

    str(weights)[:50] + '...')



ValueError: You called `set_weights(weights)` on layer "Embedding-Token" with a  weight list of length 1, but the layer was expecting 0 weights. Provided weights: [array([[-0.03812443, -0.08015507, -0.01168962, .....

**Comment by WrathofBhuvan11** [comment]
error is in this function
 load_model_weights_from_checkpoint(model,
...:                                        config,
...:                                        checkpoint_file,
...:                                        training=False)

**Comment by WrathofBhuvan11** [comment]
In [48]: loader
Out[48]: <function __main__.checkpoint_loader.<locals>._loader(name)>

In [49]: loader('bert/embeddings/word_embeddings')
Out[49]: 
array([[-0.03812443, -0.08015507, -0.01168962, ..., -0.03758528,
        -0.04412125,  0.00953547],
       [ 0.01136853, -0.02929683, -0.03054058, ..., -0.03894736,
        -0.06458649,  0.00042958],
       [-0.03499779, -0.01893356,  0.00504081, ..., -0.03684894,
        -0.03942461, -0.03027621],
       ...,
       [ 0.00039876, -0.0074348 , -0.04399593, ..., -0.03482178,
        -0.0749266 , -0.01116488],
       [-0.0215879 ,  0.00865485, -0.02265086, ..., -0.08096945,
         0.00631786, -0.03537379],
       [ 0.05276028, -0.02393056, -0.02634131, ..., -0.04740848,
        -0.04738597, -0.00887593]], dtype=float32)

In [50]: model.get_layer(name='Embedding-Token').set_weights([
    ...:     loader('bert/embeddings/word_embeddings'),
    ...: ])
Traceback (most recent call last):

  File "<ipython-input-50-a490052f65a6>", line 2, in <module>
    loader('bert/embeddings/word_embeddings'),

  File "/home/bhuvanesh/anaconda3/envs/stark/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1462, in set_weights
    str(weights)[:50] + '...')

ValueError: You called `set_weights(weights)` on layer "Embedding-Token" with a  weight list of length 1, but the layer was expecting 0 weights. Provided weights: [array([[-0.03812443, -0.08015507, -0.01168962, .....

**Comment by Santosh-Gupta** [comment]
Could you include the code you used? It's difficult to diagnose from just the error message.

**Comment by WrathofBhuvan11** [comment]
pretrained_path = "...../DocProduct/BioBertFolder/biobert_v1.0_pubmed_pmc/"
code="/DocProduct/keras_bert/loader.py"
line 58

def load_model_weights_from_checkpoint(model,
                                       config,
                                       checkpoint_file,
                                       #model.layers[1].trainable=False
                                       training=False):
    """Load trained official model from checkpoint.

    :param model: Built keras model.
    :param config: Loaded configuration file.
    :param checkpoint_file: The path to the checkpoint files, should end with '.ckpt'.
    :param training: If training, the whole model will be returned.
                     Otherwise, the MLM and NSP parts will be ignored.

here i'm getting error
in previous comment i uploaded u the single line of tht function load_model_weights_from_checkpoint

**Comment by WrathofBhuvan11** [comment]
> Could you include the code you used? It's difficult to diagnose from just the error message.

in this code https://github.com/re-search/DocProduct/blob/master/keras_bert/loader.py
pretrained_path = "...../DocProduct/BioBertFolder/biobert_v1.0_pubmed_pmc/"(this model of bioBert)
function "load_model_weights_from_checkpoint" has a problem even when i run single code snippets say
loader = checkpoint_loader(checkpoint_file)
   # model.layers[1].trainable=False

    model.get_layer(name='Embedding-Token').set_weights([
        loader('bert/embeddings/word_embeddings'),
    ])# "this line shows the same Value Error"

**Comment by Santosh-Gupta** [comment]
I'm still not sure how to exactly reproduce the error from this info. Can you give a link to the colab notebook which reproduces this error? If the error you are receiving is fully reproduced, then I can figure out where the error is coming from and possibly offer a fix.

**Comment by WrathofBhuvan11** [comment]
colab link :
"https://colab.research.google.com/drive/11hAr1qo7VCSmIjWREFwyTFblU2LVeh1R#scrollTo=ztuTHeW4jFiH&forceEdit=true&offline=true&sandboxMode=true"
#@title Load model weights and Q&A data. Double click to see code

from docproduct.predictor import RetreiveQADoc

pretrained_path = 'BioBertFolder/biobert_v1.0_pubmed_pmc/'
# ffn_weight_file = None
bert_ffn_weight_file = 'newFolder/models/bertffn_crossentropy/bertffn'
embedding_file = 'Float16EmbeddingsExpanded5-27-19.pkl'

doc = RetreiveQADoc(pretrained_path=pretrained_path,
ffn_weight_file=None,
bert_ffn_weight_file=bert_ffn_weight_file,
embedding_file=embedding_file)

**Comment by Santosh-Gupta** [comment]
That notebook doesn't seem to have an error in it. Did you mean to send a different notebook?

**Comment by WrathofBhuvan11** [comment]
No the thing is I cloned the git and downloaded same pre-trained models and
all are same but it doesn't run in my system... I need to do some
variations in the future but for now I'm unable to get this working... I'm
getting the error in loader.py script inside keras_bert folder I donno why
those lines to load the pretrained models which i downloaded are not
working...

**Comment by Santosh-Gupta** [comment]
Ah so the issue is not with the code, but with your system? 

You tried running the identical code both in colab and on your system, but the code works in colab, and not with your system?

**Comment by WrathofBhuvan11** [comment]
Yeahh but the error seems to have nothing to do with the system cuz i
personally checked whether individual modules work or not... I'm using
Tensorflow 1.9 which by default doesn't support eager execution but shld
enable with TF.enable_eager_execution()

**Comment by Santosh-Gupta** [comment]
I think I figured out your issue. You're using Tensorflow 1.9. We didn't develop this in Tensorflow 1.x, we did it in Tensorflow 2.0 alpha.

**Comment by WrathofBhuvan11** [comment]
Ok let me create a different environment for tf 2.0 alpha and see how it's
gonna work. If still any issues I'll contact you... thqs for your help
