### ISSUE TITLE
generating FFNNEmbed csv files

### ISSUE THREAD

**Issue by swayam01** [re-search/DocProduct#9]
hello, 
how do we derive the FFNNEmbed csv files for new dataset.
do we use QAEmbed or train_data_to_embedding or keras-bert feature extraction to derive the FFNNEmbeddings
Thanks

**Comment by Santosh-Gupta** [comment]
The FFNNEmbed files were when we were training the FFNN layers only, and we didn't include Bert in the training. We used Bert at a separate phase to embed the questions and answers. We initially just loaded the Bert weights and fed the questions and answers to get embeddings for each text. 

You can definitely just to train on the raw text data, and use the train train_ffn only option https://github.com/re-search/DocProduct/blob/master/docproduct/train_ffn.py

But if you have no interest in fine-tuning bert, and just want to train FFNNs, it may be help to have just the embeddings so you don't have to do the Bert forward pass at each step. Very useful for multiple epochs

You can just take our weights and use Bert as a service to create the embeddings

https://github.com/hanxiao/bert-as-service

I don't believe that we made an option to create embeddings for FFNN only training, but perhaps 
@JayYip or @ash3n did so as a side mission.

**Comment by swayam01** [comment]
Thanks a lot for the clarification
